### ISSUE TITLE
Downloading index not_found

### ISSUE THREAD

**Issue by capiscuas** [cancerian0684/dli-downloader#1]
![delete](https://cloud.githubusercontent.com/assets/515154/11006956/0de9dc94-84c7-11e5-8a3d-77134b6f2eeb.png)
Hello, thks for your software, I am not able to download the index therefore I can't search or download books.

Thks for checking.

**Comment by vistilarsen** [comment]
Thank you for a wonderful software.The existing catalog in the newest software was very helpful.
However, having the same issue as above when trying to update the indexes. 
Cannot index Sanskrit Indexes. Here's the log: 

Fetching metadata for Barcode : Indexing - Sanskrit {Total Books - 200000}
Ping to http://www.new.dli.gov.in/cgi-bin/DBscripts/allmetainfo.cgi?barcode=Indexing - Sanskrit {Total Books - 200000} was success, 200, Time (ms) : 439
Metadata not found on this server : http://www.new.dli.gov.in
Ping to http://202.41.82.144/cgi-bin/DBscripts/allmetainfo.cgi?barcode=Indexing - Sanskrit {Total Books - 200000} was success, 200, Time (ms) : 472
Metadata not found on this server : http://202.41.82.144
Ping to http://www.dli.gov.in/cgi-bin/DBscripts/allmetainfo.cgi?barcode=Indexing - Sanskrit {Total Books - 200000} was success, 200, Time (ms) : 410
Metadata not found on this server : http://www.dli.gov.in
Ping to http://www.new.dli.ernet.in/cgi-bin/DBscripts/allmetainfo.cgi?barcode=Indexing - Sanskrit {Total Books - 200000} was success, 200, Time (ms) : 467
Metadata not found on this server : http://www.new.dli.ernet.in
Ping to http://www.dli.gov.in/cgi-bin/DBscripts/allmetainfo.cgi?barcode=Indexing - Sanskrit {Total Books - 200000} was success, 200, Time (ms) : 410
Metadata not found on this server : http://www.dli.gov.in
Ping to http://www.dli.ernet.in/cgi-bin/DBscripts/allmetainfo.cgi?barcode=Indexing - Sanskrit {Total Books - 200000} was success, 200, Time (ms) : 459
Metadata not found on this server : http://www.dli.ernet.in
Ping to http://www.new1.dli.ernet.in/cgi-bin/DBscripts/allmetainfo.cgi?barcode=Indexing - Sanskrit {Total Books - 200000} was success, 200, Time (ms) : 461
Metadata not found on this server : http://www.new1.dli.ernet.in
Server URL & Metadata not found for the BarCode : Indexing - Sanskrit {Total Books - 200000}
org.shunya.dli.MetadataNotFound: Server URL & Metadata not found for the BarCode : Indexing - Sanskrit {Total Books - 200000}
    at org.shunya.dli.BarCodeInterpreter.collect(BarCodeInterpreter.java:63)
    at org.shunya.dli.DLIDownloader.fetchMetaData(DLIDownloader.java:69)
    at org.shunya.dli.DLIDownloader.fetchMetadataWithRetry(DLIDownloader.java:166)
    at org.shunya.dli.DLIDownloader.download(DLIDownloader.java:125)
    at org.shunya.dli.DownloadPanel.downloadWithRetry(DownloadPanel.java:773)
    at org.shunya.dli.DownloadPanel.access$700(DownloadPanel.java:35)
    at org.shunya.dli.DownloadPanel$6.run(DownloadPanel.java:721)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)

Download Failed for this barcode : Indexing - Sanskrit {Total Books - 200000}

**Comment by cancerian0684** [comment]
Please try latest version from this location - http://dli.shunyafoundation.com/

it does not require indexing anymore.
