### ISSUE TITLE
Not able to download DLI books

### ISSUE THREAD

**Issue by drdhaval2785** [cancerian0684/dli-downloader#3]
@cancerian0684 
I was not able to download with earlier version.
I also tried the latest 6.0.0 version.

See the attached screenshot.
Barcode was 4990010057660

![capture](https://cloud.githubusercontent.com/assets/5755132/13427529/abb97286-dfda-11e5-9f22-a3ffd32904e4.png)

**Comment by cancerian0684** [comment]
Can you please right click on the download and view logs, send it to cancerian0684@gmail.com

It must be a temporary issue.

**Comment by drdhaval2785** [comment]
Changed the download folder to D:. It was a windows issue not having access to the place where I was downloading. (Administrator permission required). Resolved.
